language: node_js
node_js:
  - "13.12"
branches:
  only:
    - master
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
script:
  - yarn install
  - yarn build
  - yarn test --watch=false
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: 19f73f12-338e-411b-81e6-485553b2cf02
  app:
    master: angular-ci