language: node_js
node_js:
  - 13.12.0
branches:
  only:
    - master
dist: xenial
addons:
  chrome: stable
before_install: # if "install" is overridden
  # Repo for Yarnsd
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost
cache:
  yarn: true
script:
  - yarn build
  - yarn test
jobs:
  include:
    - stage: test
      script:
        - echo 'Deploy!!'
        - echo 'Installing Deps!'
        - yarn
        - echo 'Testing!'
        - xvfb-run make test
        - yarn test
    - stage: deploy
      script:
        - npm install -g firebase-tools
      skip_cleanup: true
      provider: heroku
      api_key: 19f73f12-338e-411b-81e6-485553b2cf02
      app:
        master: angular-ci