language: node_js
node_js:
  - 13.12.0
branches:
  only:
    - master
before_install: # if "install" is overridden
  # Repo for Yarnsd
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
jobs:
  include:
    - stage: test
      script:
        - echo 'Deploy!!'
        - echo 'Installing Deps!'
        - yarn
        - echo 'Testing!'
        - yarn test
    - stage: deploy
      skip_cleanup: true
      provider: heroku
      api_key:  80963907-dca4-4086-9c9a-9b95f529fe4d
      app:
        master: angular-ci